# Generated by Django 2.1 on 2019-01-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20190130_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.CharField(default='Senator', max_length=100),
            preserve_default=False,
        ),
    ]
