# Generated by Django 2.1 on 2019-01-30 12:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_candidate_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vote_date', models.DateTimeField(default=datetime.datetime.now)),
                ('cois_acntent', models.TextField(max_length=200)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='votes.Candidate')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='candidate',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
